### ISSUE TITLE
MacBuilder-GUI.exe doesn't open

### ISSUE THREAD

**Issue by gevuz** [KivieDev/MacBuilder-Source#1]
First I'm not an expert and just trying to use macOS on my pc, so pardon me if I wrong asks I'm just need help. I've followed the steps and asked ChatGPT for some things I didn't know and it was pretty simple and I successed creating the MacBuilder-GUI.exe, the thing is when I try to open the app it simply create a process with same name and immediatly closes itself, I tried both normal double-click and admin option. Is there something more to do to open it?

**Comment by KivieDev** [comment]
Hello, so you cannot open the compiled exe directly you must run it on visual studio I figured out how to fix this but not a stable solution. Please build as Debug X64 and play on the editor and the issue should be resolved.

**Comment by KivieDev** [comment]
Also I forgot to mention it currently does not function, it does not build a functional EFI. It still needs some work.
